from app.Model.super_admin_model import SuperAdmin
from app.Model.etablissement_model import Etablissement
from app.Model.directeur_model import Directeur
from app.Model.classe_model import Classe
from app.Model.matiere_model import Matiere
from app.Model.professeur_model import Professeur
from app.Model.affectation_model import Affectation
from app.Model.etudiant_model import Etudiant
from app.Model.note_model import Note
from app.Model.reclamation_model import Reclamation
from app.Model.demande_releve_model import DemandeReleve
