"""empty message

Revision ID: 3e75c923a18e
Revises: 
Create Date: 2026-09-08 11:48:03.209458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e75c923a18e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('classe', sa.String(length=100), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateur')
    op.drop_table('super_admin')
    # ### end Alembic commands ###
